### ISSUE TITLE
Bad response from server: (200 [parsererror,getuisettings])

### ISSUE THREAD

**Issue by wheelerlaw** [Micka33/docker-rtorrent-rutorrent#1]
After finagling with the libtorrent and rtorrent sources (see my fork), I got it to download and build the image. But when I run it, I get this error from rutorrent:

[31.05.2015 01:22:17] Bad response from server: (200 [parsererror,getuisettings])

I have pretty much spent the day messing around with the config files and I can't seem to get it to connect to rtorrent.

**Comment by Micka33** [comment]
https://github.com/Micka33/docker-rtorrent-rutorrent/commit/f3f4de33aca71b33d23df989b3a868d0076e63da to create the rtorrent service.
And https://github.com/Micka33/docker-rtorrent-rutorrent/commit/c0d64d25907e9930051c7e202bcd4c6a23ccfa64 to try to make it work.  
not fixed yet.

**Comment by Micka33** [comment]
Fixed :)
